### ISSUE TITLE
Consider adding a package.json

### ISSUE THREAD

**Issue by aymericbeaumet** [paulsmith/angular-slugify#16]
I'm currently using [napa](https://www.npmjs.org/package/napa) to install `angular-slugify`, but I would love to be able to avoid this step and to directly use NPM.

Can you consider to add a `package.json` and publish the package to NPM?

This would be much more convenient for us (non-Bower users).

Thanks!

**Comment by paulsmith** [comment]
Thanks, closed by dc24bc6bce67092a237859ba814146f809aaf043
