### ISSUE TITLE
Release anytime soon?

### ISSUE THREAD

**Issue by bbohling** [paulsmith/angular-slugify#25]
Looks like there have been some minor (but important) updates to this repo, but no releases. Would love to see a release that includes the bump in Angular version support!

**Comment by SyntaxRules** [comment]
:+1:

**Comment by paulsmith** [comment]
Good thinking -- I just [released v1.0.1](https://github.com/paulsmith/angular-slugify/releases/tag/v1.0.1).

**Comment by SyntaxRules** [comment]
Thanks!

**Comment by bbohling** [comment]
Excellent, thanks!
