### ISSUE TITLE
Update angular dependency

### ISSUE THREAD

**Issue by dsferruzza** [paulsmith/angular-slugify#8]
Hi!

Would that be possible to update `bower.json`?
It needs angular 1.0.7 whereas the latest stable is 1.2.9.

*It could also be a good idea not to reference a specific version but something like `1.2.*` or `1.*` or even `*`.*

Thanks!

**Comment by SyntaxRules** [comment]
:+1: Yes please!

My vote is ">=1.0.0".

**Comment by paulsmith** [comment]
Thanks, closed by b59737b
